// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MediaToolkit.Resources
{     
	public partial class AssemblyInfo
	{
		public const int Day = 20;  
		public const int Month = 12; 
		public const int Year = 2019;

		public const string Copyright = "Copyright © ___ CO Ltd. 2019";
		public const string Company = "___ CO Ltd.";

		public const string Version = "1.0.0.0";
	}
}